services:
  postgres:
    image: postgres:latest
    container_name: mySqlV1
    environment:
      POSTGRES_DB: demo
      POSTGRES_USER: har
      POSTGRES_PASSWORD: har
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
